name: gpx
description: Package for load, manipulate, and save GPS data in GPX format (a light-weight XML data format for the interchange of GPS data - waypoints, routes, and tracks).
version: 1.1.1
homepage: https://github.com/kb0/dart-gpx/

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  quiver: ">=0.22.0 <4.0.0"
  xml: ^5.0.2

dev_dependencies:
  test: ^1.16.5
